version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - SSL_CERT=${SSL_CERT}
        - SSL_KEY=${SSL_KEY}
        - DOLLAR_SIGN=${DOLLAR_SIGN}
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www
    container_name: nginx
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        - MYSQL_NAME=${MYSQL_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ROOT=${MYSQL_ROOT}
    ports:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        - MYSQL_NAME=${MYSQL_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 9000
    volumes:
      - wp-volume:/var/www
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
networks:
  inception:
